version: '3.8'

services:
  trading-engine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_ALPACA=true
        - INSTALL_CCXT=true
        - INSTALL_DEV=false
        - INSTALL_BACKTRADER=false
    command: python -m uvicorn dashboard.backend.main:app --host 0.0.0.0 --port 8000
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: trades
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d trades"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redis-data: